export const APP_INIT = 'APP_INIT';
export const IMAGE_PAGE_INIT = 'IMAGE_PAGE_INIT';
export const IMAGE_DESCRIPTION_UPDATED = 'IMAGE_DESCRIPTION_UPDATED';
export const IMAGE_DELETED = 'IMAGE_DELETED';